version: "3.8"
services:
  web:
    image: nginx:alpine
    container_name: landing-araceli
    ports:
      - 9500:3000
    volumes:
      - ./site:/usr/share/nginx/html:ro
    restart: unless-stopped
